### ISSUE TITLE
binary_tree_parse() no reconoce el caracter _

### ISSUE THREAD

**Issue by aledomu** [migueltoro/C#1]
Falla con las siguientes líneas:

```
0(_,-1)
12(-34,56(-78,_))
```

El error es el siguiente:

```
caracter _ no reconocido en fichero ..\types\tokenizer.c linea 221 
Assertion failed!

Program: C:\Users\user\eclipse\cpp\workspace\PI2B-C-alumno\Debug\PI2B-C-alumno.exe
File: ..\types\preconditions.c, Line 16

Expression: false
```

**Comment by migueltoro** [comment]
Alejandro, efectivamente había un error el el código.

He dejado actualializado el código en github perosi no quieres volverte a
bajar la nueva versión modifica la linea 203 del fichero
tokenizer.c por:

 } else if (is_alphabetic_char(c) || c == '_') {

Así debe funcionar.

Saludos

Miguel Toro
